# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ConvertTo_Daily <- function(w, aggregateFun) {
    .Call('_tdata_ConvertTo_Daily', PACKAGE = 'tdata', w, aggregateFun)
}

.ConvertTo_MultiDaily <- function(w, k, aggregateFun, fromEnd) {
    .Call('_tdata_ConvertTo_MultiDaily', PACKAGE = 'tdata', w, k, aggregateFun, fromEnd)
}

.ConvertTo_Weekly <- function(w, weekStart, aggregateFun) {
    .Call('_tdata_ConvertTo_Weekly', PACKAGE = 'tdata', w, weekStart, aggregateFun)
}

.ConvertTo_XxYear <- function(w, aggregateFun, x) {
    .Call('_tdata_ConvertTo_XxYear', PACKAGE = 'tdata', w, aggregateFun, x)
}

.F_cross_section <- function(position) {
    .Call('_tdata_F_CrossSection', PACKAGE = 'tdata', position)
}

.F_yearly <- function(year) {
    .Call('_tdata_F_Yearly', PACKAGE = 'tdata', year)
}

.F_quarterly <- function(year, quarter) {
    .Call('_tdata_F_Quarterly', PACKAGE = 'tdata', year, quarter)
}

.F_monthly <- function(year, month) {
    .Call('_tdata_F_Monthly', PACKAGE = 'tdata', year, month)
}

.F_multi_yearly <- function(year, z) {
    .Call('_tdata_F_MultiYearly', PACKAGE = 'tdata', year, z)
}

.F_x_times_a_year <- function(year, x, position) {
    .Call('_tdata_F_XTimesAYear', PACKAGE = 'tdata', year, x, position)
}

.F_x_times_z_years <- function(year, x, z, position) {
    .Call('_tdata_F_XTimesZYears', PACKAGE = 'tdata', year, x, z, position)
}

.F_weekly <- function(year, month, day) {
    .Call('_tdata_F_Weekly', PACKAGE = 'tdata', year, month, day)
}

.F_multi_weekly <- function(year, month, day, k) {
    .Call('_tdata_F_MultiWeekly', PACKAGE = 'tdata', year, month, day, k)
}

.F_daily <- function(year, month, day) {
    .Call('_tdata_F_Daily', PACKAGE = 'tdata', year, month, day)
}

.F_multi_daily <- function(year, month, day, k) {
    .Call('_tdata_F_MultiDaily', PACKAGE = 'tdata', year, month, day, k)
}

.F_daily_in_week <- function(year, month, day, weekStart, weekEnd, forward) {
    .Call('_tdata_F_DailyInWeek', PACKAGE = 'tdata', year, month, day, weekStart, weekEnd, forward)
}

.F_list_string <- function(items, value) {
    .Call('_tdata_F_ListString', PACKAGE = 'tdata', items, value)
}

.F_list_date <- function(items, value) {
    .Call('_tdata_F_ListDate', PACKAGE = 'tdata', items, value)
}

.F_hourly <- function(day, hour) {
    .Call('_tdata_F_Hourly', PACKAGE = 'tdata', day, hour)
}

.F_minutely <- function(day, minute) {
    .Call('_tdata_F_Minutely', PACKAGE = 'tdata', day, minute)
}

.F_secondly <- function(day, second) {
    .Call('_tdata_F_Secondly', PACKAGE = 'tdata', day, second)
}

.F_x_times_a_day <- function(day, x, position) {
    .Call('_tdata_F_XTimesADay', PACKAGE = 'tdata', day, x, position)
}

.ToString_F <- function(value) {
    .Call('_tdata_ToString_F', PACKAGE = 'tdata', value)
}

.ToClassString_F <- function(value) {
    .Call('_tdata_ToClassString_F', PACKAGE = 'tdata', value)
}

.ToString_F0 <- function(value) {
    .Call('_tdata_ToString_F0', PACKAGE = 'tdata', value)
}

.Parse_F <- function(str, classStr) {
    .Call('_tdata_Parse_F', PACKAGE = 'tdata', str, classStr)
}

.Sequence_F0 <- function(start, length, by) {
    .Call('_tdata_Sequence_F0', PACKAGE = 'tdata', start, length, by)
}

.Sequence_F <- function(from, to, by) {
    .Call('_tdata_Sequence_F', PACKAGE = 'tdata', from, to, by)
}

.F_GetClass <- function(name) {
    .Call('_tdata_F_GetClass', PACKAGE = 'tdata', name)
}

.F_Next <- function(freq, steps) {
    .Call('_tdata_F_Next', PACKAGE = 'tdata', freq, steps)
}

.F_Minus <- function(freq1, freq2) {
    .Call('_tdata_F_Minus', PACKAGE = 'tdata', freq1, freq2)
}

.Get_Descriptive <- function(w, type, skipNAN) {
    .Call('_tdata_Get_Descriptive', PACKAGE = 'tdata', w, type, skipNAN)
}

.Variable <- function(data, name, startFrequency, fields) {
    .Call('_tdata_Variable', PACKAGE = 'tdata', data, name, startFrequency, fields)
}

.VariableToString <- function(w) {
    .Call('_tdata_VariableToString', PACKAGE = 'tdata', w)
}

.BindVariables <- function(varList, interpolate, adjustLeadLags, numExo, horizon) {
    .Call('_tdata_BindVariables', PACKAGE = 'tdata', varList, interpolate, adjustLeadLags, numExo, horizon)
}

